CREATE DATABASE IF NOT EXISTS `atl-auth-db`;
CREATE DATABASE IF NOT EXISTS `ims-academic-db`;
CREATE DATABASE IF NOT EXISTS `ims-student-db`;
CREATE DATABASE IF NOT EXISTS `ims-instructor-db`;
CREATE DATABASE IF NOT EXISTS `ims-staff-db`;
CREATE DATABASE IF NOT EXISTS `ims-finance-db`;