spring.application.name=atl-mcq-service
server.servlet.context-path=/mcq


spring.data.mongodb.uri=mongodb+srv://atl_admin_user:atlAdmin@123@atl-cluster.tvh7a2e.mongodb.net/?retryWrites=true&w=majority&appName=atl-cluster
