spring.application.name=ims-staff-service
# server.servlet.context-path=/ims-staff
server.port=8086

#MySql Database Config
spring.datasource.url=${STAFF_DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Service Discovery
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30