spring.application.name=atl-auth-service
server.port=8081

# H2 Database Configuration
#spring.datasource.url=jdbc:h2:file:~/data/atldb_auth;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#MySql Database Config
spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
# Use 'update' to keep your schema synchronized or 'none' for manual management

# Enable H2 console for easy access during development (optional)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
atl.jwt.secret=${AUTH_JWT_SECRET}

#Redis config.
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:abc}
spring.data.redis.ssl.enabled=true

# Gmail SMTP server settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${AUTH_EMAIL}
spring.mail.password=${AUTH_MAIL_PASS}

# Enable TLS and authentication
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true


#logging.level.org.springframework.security=DEBUG

#Service Discovery
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30