spring.application.name=atl-auth-service
server.servlet.context-path=/atl-auth
server.port=8081

# H2 Database Configuration
#spring.datasource.url=jdbc:h2:file:~/data/atldb_auth;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#MySql Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/atl-auth-db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=my-secret-atl

# Hibernate settings
spring.jpa.hibernate.ddl-auto=create
# Use 'update' to keep your schema synchronized or 'none' for manual management

# Enable H2 console for easy access during development (optional)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
atl.jwt.secret=strongjwt_secret-this-is-my-super-secret