spring.application.name=atl-gateway-service
server.servlet.context-path=/atl-gateway
# JWT Secret
atl.jwt.secret=strongjwt_secret-this-is-my-super-secret

# Route to course-service
spring.cloud.gateway.routes[0].id=course-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082

# Match full path including context path
spring.cloud.gateway.routes[0].predicates[0]=Path=/atl-gateway/atl-courses/**

# Rewrite to /atl/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/atl-gateway/atl-courses/(?<segment>.*), /atl/${segment}
