spring.application.name=atl-gateway-service
server.servlet.context-path=/atl-gateway
# JWT Secret
atl.jwt.secret=${AUTH_JWT_SECRET}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#CORS CONFIG..
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=https://6000-firebase-studio-1761369370077.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true


#Redirect to Auth Service.
spring.cloud.gateway.routes[2].id=atl-auth-service
spring.cloud.gateway.routes[2].uri=lb://atl-auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/atl-gateway/atl-auth/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/atl-gateway/atl-auth/(?<segment>.*), /atl-auth/${segment}

#Redirect to Student service
spring.cloud.gateway.routes[3].id=ims-student-service
spring.cloud.gateway.routes[3].uri=lb://ims-student-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/atl-gateway/ims-student/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/atl-gateway/ims-student/(?<segment>.*), /ims-student/${segment}

#Redirect to Instructor service
spring.cloud.gateway.routes[4].id=ims-instructor-service
spring.cloud.gateway.routes[4].uri=lb://ims-instructor-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/atl-gateway/ims-instructor/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/atl-gateway/ims-instructor/(?<segment>.*), /ims-instructor/${segment}

#Redirect to Staff service
spring.cloud.gateway.routes[1].id=ims-staff-service
spring.cloud.gateway.routes[1].uri=lb://ims-staff-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/atl-gateway/ims-staff/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/atl-gateway/ims-staff/(?<segment>.*), /ims-staff/${segment}

#Redirect to Academic service
spring.cloud.gateway.routes[0].id=ims-academic-service
spring.cloud.gateway.routes[0].uri=lb://ims-academic-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/atl-gateway/ims-academic/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/atl-gateway/ims-academic/(?<segment>.*), /ims-academic/${segment}

# --- Gateway Security Config ---
atl.gateway.security.public-paths[0]=/atl-auth/auth/signup
atl.gateway.security.public-paths[1]=/atl-auth/auth/signin
atl.gateway.security.public-paths[2]=/atl-auth/auth/otp/sendOtp
atl.gateway.security.public-paths[3]=/atl-auth/auth/otp/verifyOtp
atl.gateway.security.public-paths[4]=/atl-auth/auth/forgot-password/initiate
atl.gateway.security.public-paths[5]=/atl-auth/auth/forgot-password/verify-otp
atl.gateway.security.public-paths[6]=/atl-auth/auth/forgot-password/reset
atl.gateway.security.public-paths[7]=/atl-auth/auth/onboard-admin

atl.gateway.security.role-paths./ims-student/students=TEACHER,ADMIN,TENANT_ADMIN
atl.gateway.security.role-paths./ims-instructor/instructors=ADMIN,TENANT_ADMIN
atl.gateway.security.role-paths./ims-staff/staff=ADMIN,TENANT_ADMIN
