spring.application.name=atl-gateway-service
# server.servlet.context-path=/atl-gateway
# JWT Secret
atl.jwt.secret=${AUTH_JWT_SECRET}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#CORS CONFIG..
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true


# --- Dynamic Discovery Routing ---
# Routes are automatically resolved via discovery locator (lower-case-service-id)
# e.g. /atl-gateway/atl-auth-service/** -> atl-auth-service

# --- Gateway Security Config ---
atl.gateway.security.public-paths[0]=/atl-auth-service/auth/signin
atl.gateway.security.public-paths[1]=/atl-auth-service/auth/otp/sendOtp
atl.gateway.security.public-paths[2]=/atl-auth-service/auth/otp/verifyOtp
atl.gateway.security.public-paths[3]=/atl-auth-service/auth/forgot-password/initiate
atl.gateway.security.public-paths[4]=/atl-auth-service/auth/forgot-password/verify-otp
atl.gateway.security.public-paths[5]=/atl-auth-service/auth/forgot-password/reset
atl.gateway.security.public-paths[6]=/atl-auth-service/auth/onboard-admin
atl.gateway.security.public-paths[7]=/ims-platform-service/api/v1/platform/public/**

atl.gateway.security.role-paths./ims-student-service/students=INSTRUCTOR,ADMIN,TENANT_ADMIN
atl.gateway.security.role-paths./ims-instructor-service/instructors=INSTRUCTOR,ADMIN,TENANT_ADMIN
atl.gateway.security.role-paths./ims-staff-service/staff=ADMIN,TENANT_ADMIN
atl.gateway.security.role-paths./ims-student-service/enrollments=STUDENT,INSTRUCTOR,ADMIN,TENANT_ADMIN
atl.gateway.security.role-paths./ims-instructor-service/offering-instructors=INSTRUCTOR,ADMIN,TENANT_ADMIN
atl.gateway.security.role-paths./ims-finance-service/api/v1/finance=TENANT_ADMIN,ACCOUNTANT,STUDENT,GUARDIAN,PARENT
atl.gateway.security.role-paths./ims-inventory-service/api/v1/inventory=TENANT_ADMIN
atl.gateway.security.role-paths./ims-reports-service/api/v1/reports/generate=TENANT_ADMIN,ADMIN
atl.gateway.security.role-paths./ims-platform-service/api/v1/platform/admin/**=SUPER_ADMIN

