spring.application.name=ims-notification-service
server.port=8090


# Gmail SMTP server settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${AUTH_EMAIL}
spring.mail.password=${AUTH_MAIL_PASS}

# Enable TLS and authentication
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JWT Secret
atl.jwt.secret=${AUTH_JWT_SECRET}

#Redis config.
spring.data.cache.type=redis
spring.data.redis.host=${REDIS_URL}
spring.data.redis.port=6379

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true