spring.application.name=ims-inventory-service

server.port=8089

#MySql Database Config
spring.datasource.url=${INVENTORY_MYSQL_URI:jdbc:mysql://localhost:3306/ims_inventory_db?createDatabaseIfNotExist=true}
spring.datasource.username=${INVENTORY_MYSQL_USER:root}
spring.datasource.password=${INVENTORY_MYSQL_PASS:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Service Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
