input {
    tcp {
        port => 5044
        codec => json # Expects structured JSON logs
    }
}
output {
    elasticsearch {
        # Logstash uses the internal service name 'elasticsearch'
        hosts => ["http://elasticsearch:9200"]
        index => "microservice-logs-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
}